---


- hosts: [vagrant-db]
  sudo: yes
  user: vagrant
  roles:
    - common
    - db
  vars_files:
    - vars/app.yml

- hosts: [vagrant-web]
  serial: 1
  sudo: yes
  user: vagrant
  roles:
    - common
    - app
  vars_files:
    - vars/app.yml
