---

- name: restart postgres
  service: name=postgresql state=restarted

- name: reload pg_ctl
  command: /usr/lib/postgresql/9.3/bin/pg_ctl -D /var/lib/postgresql/9.3/main/ reload
  sudo_user: postgres
  sudo: True
